name: Data Information Literacy
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
include: ["cornell.jpg", "dil12.png", "facebook.png", "imls.jpg", "pulib.png", "twitter.png", "umn.jpg", "uo.jpg"]
