name: Data Information Literacy
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
keep_files: [images/cornell.jpg, images/dil12.png, images/facebook.png, images/imls.jpg, images/pulib.png, images/twitter.png, images/umn.jpg, images/uo.jpg]
